#@data/values
---
releases:
  - name: capi-k8s-release
    github_release: false
    vendir_github_release: false
  - name: eirini-release
    github_org: cloudfoundry-incubator
    build_dir: "build/eirini"
  - name: metric-proxy